/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JDialog;

/**
 *
 * @author douglas
 */
public class PkInstancia extends javax.swing.JFrame {

    /**
     * Creates new form PkInstancia
     */
    public PkInstancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastrar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MenuCadastrarInstancia = new javax.swing.JMenuItem();
        MenuCadastrarRecurso = new javax.swing.JMenuItem();
        MenuCadastrarRecursoDisponivel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PkInstancia");
        setLocation(new java.awt.Point(0, 0));
        setName("PkInstancia"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        MenuCadastrar.setText("Arquivos");

        jMenu1.setText("Instância");

        MenuCadastrarInstancia.setText("Instância");
        MenuCadastrarInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarInstanciaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastrarInstancia);

        MenuCadastrarRecurso.setText("Recurso");
        jMenu1.add(MenuCadastrarRecurso);

        MenuCadastrarRecursoDisponivel.setText("Recurso Disponível");
        jMenu1.add(MenuCadastrarRecursoDisponivel);

        MenuCadastrar.add(jMenu1);

        jMenuBar1.add(MenuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarInstanciaActionPerformed
        FormInstancia formInstancia = new FormInstancia(this, true);
        formInstancia.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        formInstancia.setTitle("Formulário de Instância");
        formInstancia.setLocationRelativeTo(null);
        formInstancia.setResizable(false);
        formInstancia.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarInstanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PkInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PkInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PkInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PkInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PkInstancia pkInstancia = new PkInstancia();
                // Inicialisa o form no meio da tela
                pkInstancia.setLocationRelativeTo(null);
                pkInstancia.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenuItem MenuCadastrarInstancia;
    private javax.swing.JMenuItem MenuCadastrarRecurso;
    private javax.swing.JMenuItem MenuCadastrarRecursoDisponivel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
